### ISSUE TITLE
New order always Fries and Ice Cream

### ISSUE THREAD

**Issue by masonelmore** [FreeMasen/GroupProject2#14]
The Main Course is always Fries and the Dessert is always Ice Cream no matter what is selected in the pickerviewthing in the New Order view.

**Comment by FreeMasen** [comment]
func pickerView(pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) 

is possibly the issue? 

It could also be reading incorrectly from the order object.  have you validated that the order object has the same properties it is displaying?

I ran into an issue this weekend where I was only populating the first cell in tableview section, this can cause the data to be flawed.

**Comment by FreeMasen** [comment]
I just tested it in master, I am not having that issue.
