### ISSUE TITLE
Add Item Screen

### ISSUE THREAD

**Issue by FreeMasen** [FreeMasen/GroupProject2#3]
- New Item not added to Tableview
  - SQLite Helper saving properly?
  - Menu Object get items working properly?
  - reload data firing during event?

**Comment by FreeMasen** [comment]
Discovered that the issue is related to the SQLiteHelper class deleting the database file every time the getitemsformenu method is called. Moving this to the ViewDidLoad on first view.  Updating the SQLiteHelper Issue to look for a solution to this.

**Comment by masonelmore** [comment]
I wonder if we should make a method for the SQLHelper class called prepareSeedData().  We should only have to do that at the start of the program and not every time we need to get items from the database.

**Comment by FreeMasen** [comment]
I think both of your comments are probably more appropriate.  I have a bunch of changes that I was not able to commit before my lunch ended today.  I will try and submit those when I get home.  Hopefully I will be able to get that done tonight.

**Comment by FreeMasen** [comment]
This is now working as expected.
