### ISSUE TITLE
Add Checkout view

### ISSUE THREAD

**Issue by FreeMasen** [FreeMasen/GroupProject2#4]
- Add view controller for checkout process
  - Needs text field for items and costs
  - Needs to display subtotal, Tax, Total
  - Button that mimics checking out and removing the order from the table?

**Comment by MuffinUprising** [comment]
Added the things in the list. There may be a merge conflict with the storyboard... be careful.

**Comment by FreeMasen** [comment]
I show the class file on Casey fork but not in master.
TODO:
- Add back to Storyboard
- Wire up controls
- Add segue to view
  - segue should be called from didSelectItemAtIndexPath
  - segue should pass selected order object to CheckoutViewController
  - segue should pass table reference to CheckoutViewController to remove order from table at serving floor level
