### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by FreeMasen** [FreeMasen/GroupProject2#6]
- All
  - Use the method Mason used to store how many tables have been created to control indexing or objects?
- Order
  - Add tax and subtotal computed variables
- Menu
  - Should this class be a singleton?
- Order
  - Implement the Remove option
- Table
  - update init to take no variables
- ServingFloor
  - Implement this class as a singleton?
  - Include a list of tables
  - include a list of server names 
  - put instance in the global score
  - method for adding and removing tables

**Comment by FreeMasen** [comment]
- All
  - Use the method Mason used to store how many tables have been created to control indexing or objects?
- ~~Order~~
  - ~~Add tax and subtotal computed variables~~
- Menu
  - Should this class be a singleton?
- ~~Order~~
  - ~~Implement the Remove option~~
- Table
  - ~~update init to take no variables~~
- ServingFloor
  - Implement this class as a singleton?
  - ~~Include a list of tables~~
  - ~~include a list of server names ~~
  - ~~put instance in the global score~~
  - ~~method for adding and removing tables~~

**Comment by masonelmore** [comment]
What do you think about having a method for the SQLHelper class called getMenu() that returns a Menu object with the menu data inside it?

**Comment by FreeMasen** [comment]
That is a great idea.
